"""Private Backend Workspace execution and filesystem domain."""

from cli_agent.runtime._backend.execution import _FilesystemExecution
from cli_agent.runtime._backend.facts import (
    _CapabilityInspection,
    _CapabilitySource,
    _CapabilityState,
    _DirectoryEntry,
    _FileEdit,
    _FileEditRequest,
    _FileEditResult,
    _FileMetadata,
    _FilesystemError,
    _FileWriteRequest,
    _FileWriteResult,
    _MCPServerFacts,
    _MCPToolFacts,
    _ResolvedPath,
    _ShellExecutionRequest,
    _ToolBinding,
    _ToolExecutionRequest,
    _ToolRuntimeStatus,
    _WorkspaceSource,
)
from cli_agent.runtime._backend.protocol import (
    _Backend,
    _BackendWorkspace,
    _BoundCapabilityView,
    _WorkspaceFilesystem,
    _WorkspaceMCPRuntime,
)

__all__ = [
    "_Backend",
    "_BackendWorkspace",
    "_BoundCapabilityView",
    "_CapabilityInspection",
    "_CapabilitySource",
    "_CapabilityState",
    "_DirectoryEntry",
    "_FileEdit",
    "_FileEditRequest",
    "_FileEditResult",
    "_FileMetadata",
    "_FileWriteRequest",
    "_FileWriteResult",
    "_FilesystemError",
    "_FilesystemExecution",
    "_MCPServerFacts",
    "_MCPToolFacts",
    "_ResolvedPath",
    "_ShellExecutionRequest",
    "_ToolBinding",
    "_ToolExecutionRequest",
    "_ToolRuntimeStatus",
    "_WorkspaceFilesystem",
    "_WorkspaceMCPRuntime",
    "_WorkspaceSource",
]
