"""Runtime-open Skill Catalog derived from the Capability View."""

from __future__ import annotations

from pathlib import Path

from cli_agent.runtime._capability.skills.facts import SkillEntry
from cli_agent.runtime._capability.skills.parser import (
    SkillParseError,
    find_skill_md,
    parse_frontmatter,
    validate,
)
from cli_agent.runtime._capability.view import _CapabilityView
from cli_agent.runtime._capability.workspace import _atomic_write


class _SkillCatalog:
    """Immutable lookup and generated projections for effective Skills."""

    def __init__(self, entries: tuple[SkillEntry, ...]) -> None:
        """Hold the immutable entries and index them by name for lookup."""

        self.entries = entries
        self._by_name = {entry.name: entry for entry in entries}

    @classmethod
    def reconcile(cls, capability_view: _CapabilityView) -> _SkillCatalog:
        """Build trusted entries and atomically refresh the derived index."""

        skills_directory = capability_view.root / "skills"
        candidates = sorted(
            (
                path
                for path in skills_directory.iterdir()
                if path.is_dir()
            ),
            key=lambda path: path.name,
        )
        entries = tuple(
            entry
            for entry in (
                _inspect_skill(path, capability_view) for path in candidates
            )
            if entry is not None
        )
        catalog = cls(entries)
        _atomic_write(
            skills_directory / "index.md",
            catalog.render_index().encode("utf-8"),
        )
        return catalog

    def get(self, name: str) -> SkillEntry | None:
        """Return the entry for one skill name, or None if absent."""

        return self._by_name.get(name)

    @property
    def valid_entries(self) -> tuple[SkillEntry, ...]:
        """Return only the entries that passed structural validation."""

        return tuple(entry for entry in self.entries if entry.valid)

    def render_index(self) -> str:
        """Render the model-readable projection without creating authority."""

        if not self.entries:
            return "# Skills\n\n_no skills_\n"

        lines = [
            "# Skills",
            "",
            (
                "Generated by cli-agent from the Runtime-open Capability View. "
                "This file is not an authority for validation or scheduling."
            ),
            "",
            "| Name | Status | Provenance | Shadows Repertoire | Summary |",
            "|---|---|---|---|---|",
        ]
        for entry in self.entries:
            lines.append(
                "| {name} | {status} | {provenance} | {shadows} | {summary} |".format(
                    name=_markdown_cell(entry.name),
                    status=(
                        "valid"
                        if entry.valid
                        else f"invalid: {entry.validation_error or 'unknown error'}"
                    ).replace("|", "\\|"),
                    provenance=entry.provenance or "unknown",
                    shadows="yes" if entry.shadows_repertoire else "no",
                    summary=_markdown_cell(entry.summary),
                )
            )
        return "\n".join(lines) + "\n"

    def render_info(self, name: str) -> tuple[str, bool]:
        """Render a human-readable report for one skill and its found flag."""

        entry = self.get(name)
        if entry is None:
            return f"Skill not found: {name}\n", False

        lines = [
            f"# Skill: {entry.name}",
            "",
            f"- Status: {'valid' if entry.valid else 'invalid'}",
            f"- Provenance: {entry.provenance or 'unknown'}",
            (
                "- Shadows Repertoire: "
                f"{'yes' if entry.shadows_repertoire else 'no'}"
            ),
        ]
        if entry.validation_error:
            lines.append(f"- Validation error: {entry.validation_error}")
        lines.extend(
            [
                "",
                entry.description
                or f"Skill {entry.name} exists, but no description was found.",
            ]
        )
        return "\n".join(lines).rstrip() + "\n", True


def _inspect_skill(
    path: Path,
    capability_view: _CapabilityView,
) -> SkillEntry | None:
    """Build one SkillEntry from a candidate directory, or None if whiteouted."""

    name = path.name
    relative = Path("skills") / name / "SKILL.md"
    provenance = None
    shadows = False
    validation_error: str | None = None

    try:
        inspection = capability_view.inspect(relative)
    except ValueError as exc:
        validation_error = str(exc)
    else:
        if inspection.provenance == "whiteout":
            return None
        if inspection.provenance in {"repertoire", "workspace"}:
            provenance = inspection.provenance
        shadows = inspection.shadows_repertoire

    if validation_error is None:
        errors = validate(path)
        if errors:
            validation_error = "; ".join(errors)

    return SkillEntry(
        name=name,
        path=path,
        skill_md=path / "SKILL.md",
        provenance=provenance,
        shadows_repertoire=shadows,
        valid=validation_error is None,
        validation_error=validation_error,
        description=(
            None if validation_error is not None else _read_description(path)
        ),
    )


def _read_description(path: Path) -> str | None:
    """Read the frontmatter description, or None when unavailable."""

    skill_md = find_skill_md(path)
    if skill_md is None:
        return None
    try:
        content = skill_md.read_text(encoding="utf-8")
        metadata = parse_frontmatter(content)
    except (OSError, UnicodeError, SkillParseError):
        return None
    description = metadata.get("description")
    return description if isinstance(description, str) else None


def _markdown_cell(value: str) -> str:
    """Escape a value so it is safe inside one Markdown table cell."""

    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")
