"""Runtime-open Skill Catalog discovered from logical capability source."""

from __future__ import annotations

from cli_agent.runtime._capability.facts import _FilesystemError
from cli_agent.runtime._capability.skills.facts import SkillEntry
from cli_agent.runtime._capability.skills.parser import (
    SkillParseError,
    parse_frontmatter,
    validate_skill,
)
from cli_agent.runtime._capability.source_view import CapabilitySource

_SKILL_MD_FILENAME = "SKILL.md"


class _SkillCatalog:
    """Immutable lookup and generated projections for effective Skills."""

    def __init__(self, entries: tuple[SkillEntry, ...]) -> None:
        """Hold the immutable entries and index them by name for lookup."""

        self.entries = entries
        self._by_name = {entry.name: entry for entry in entries}

    @classmethod
    async def discover(
        cls,
        capability_view: CapabilitySource,
    ) -> _SkillCatalog:
        """Build trusted entries from one logical capability view.

        Discovery and validation only read the view; no projection is
        written and no process or resource is created.
        """

        listing = await capability_view.list("skills")
        candidates = sorted(
            (entry.name for entry in listing if entry.metadata.kind == "directory"),
        )
        entries: list[SkillEntry] = []
        for name in candidates:
            entry = await _inspect_skill(capability_view, name)
            if entry is not None:
                entries.append(entry)
        return cls(tuple(entries))

    def get(self, name: str) -> SkillEntry | None:
        """Return the entry for one skill name, or None if absent."""

        return self._by_name.get(name)

    @property
    def valid_entries(self) -> tuple[SkillEntry, ...]:
        """Return only the entries that passed structural validation."""

        return tuple(entry for entry in self.entries if entry.valid)

    def render_index(self) -> str:
        """Render the model-readable projection without creating authority."""

        if not self.entries:
            return "# Skills\n\n_no skills_\n"

        lines = [
            "# Skills",
            "",
            (
                "Generated by cli-agent from the Runtime-open Capability View. "
                "This file is not an authority for validation or scheduling."
            ),
            "",
            "| Name | Status | Provenance | Shadows Repertoire | Summary |",
            "|---|---|---|---|---|",
        ]
        for entry in self.entries:
            lines.append(
                "| {name} | {status} | {provenance} | {shadows} | {summary} |".format(
                    name=_markdown_cell(entry.name),
                    status=(
                        "valid"
                        if entry.valid
                        else f"invalid: {entry.validation_error or 'unknown error'}"
                    ).replace("|", "\\|"),
                    provenance=entry.provenance or "unknown",
                    shadows="yes" if entry.shadows_repertoire else "no",
                    summary=_markdown_cell(entry.summary),
                )
            )
        return "\n".join(lines) + "\n"

    def render_info(self, name: str) -> tuple[str, bool]:
        """Render a human-readable report for one skill and its found flag."""

        entry = self.get(name)
        if entry is None:
            return f"Skill not found: {name}\n", False

        lines = [
            f"# Skill: {entry.name}",
            "",
            f"- Status: {'valid' if entry.valid else 'invalid'}",
            f"- Provenance: {entry.provenance or 'unknown'}",
            (f"- Shadows Repertoire: {'yes' if entry.shadows_repertoire else 'no'}"),
        ]
        if entry.validation_error:
            lines.append(f"- Validation error: {entry.validation_error}")
        lines.extend(
            [
                "",
                entry.description
                or f"Skill {entry.name} exists, but no description was found.",
            ]
        )
        return "\n".join(lines).rstrip() + "\n", True


async def _inspect_skill(
    capability_view: CapabilitySource,
    name: str,
) -> SkillEntry | None:
    """Build one SkillEntry from a candidate directory, or None if whiteouted."""

    skill_md = f"skills/{name}/SKILL.md"
    provenance = None
    shadows = False
    validation_error: str | None = None

    try:
        inspection = await capability_view.inspect(skill_md)
    except ValueError as exc:
        validation_error = str(exc)
    else:
        if inspection.provenance == "whiteout":
            return None
        if inspection.provenance in {"repertoire", "workspace"}:
            provenance = inspection.provenance
        shadows = inspection.shadows_repertoire

    if validation_error is None:
        validation_error = await _validate_skill_view(capability_view, name)

    description = (
        None
        if validation_error is not None
        else await _read_description(capability_view, name)
    )
    return SkillEntry(
        name=name,
        path=f"skills/{name}",
        skill_md=skill_md,
        provenance=provenance,
        shadows_repertoire=shadows,
        valid=validation_error is None,
        validation_error=validation_error,
        description=description,
    )


async def _validate_skill_view(
    capability_view: CapabilitySource,
    name: str,
) -> str | None:
    """Return the aggregated Skill validation error, or None when valid."""

    try:
        listing = await capability_view.list(f"skills/{name}")
    except _FilesystemError:
        return f"not a directory: {name}"
    if _SKILL_MD_FILENAME not in {entry.name for entry in listing}:
        return "missing required file: SKILL.md"
    try:
        content = (await capability_view.read(f"skills/{name}/SKILL.md")).decode(
            "utf-8"
        )
    except (UnicodeDecodeError, _FilesystemError) as exc:
        return f"SKILL.md is not readable UTF-8: {exc}"
    errors = validate_skill(content, directory_name=name)
    if not errors:
        return None
    return "; ".join(errors)


async def _read_description(
    capability_view: CapabilitySource,
    name: str,
) -> str | None:
    """Read the frontmatter description, or None when unavailable."""

    try:
        content = (await capability_view.read(f"skills/{name}/SKILL.md")).decode(
            "utf-8"
        )
        metadata = parse_frontmatter(content)
    except (UnicodeDecodeError, _FilesystemError, SkillParseError):
        return None
    description = metadata.get("description")
    return description if isinstance(description, str) else None


def _markdown_cell(value: str) -> str:
    """Escape a value so it is safe inside one Markdown table cell."""

    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")
