"""Runtime-open Tool Catalog derived from the Capability View."""

from __future__ import annotations

import ast
import keyword
from collections.abc import Callable
from pathlib import Path

from cli_agent.runtime._backend import _BoundCapabilityView
from cli_agent.runtime._capability.tools.facts import ToolEntry
from cli_agent.runtime._capability.workspace import _atomic_write
from cli_agent.runtime.diagnostic import RuntimeDiagnostic

_PARALLEL_SAFE_NAME = "PARALLEL_SAFE"
_MCP_TOOL_PREFIX = "mcp_"


class _ToolCatalog:
    """Immutable lookup and generated projections for effective Tool files."""

    def __init__(self, entries: tuple[ToolEntry, ...]) -> None:
        self.entries = entries
        self._by_name = {entry.name: entry for entry in entries}

    @classmethod
    async def reconcile(
        cls,
        capability_view: _BoundCapabilityView,
        on_diagnostic: Callable[[RuntimeDiagnostic], None] | None = None,
    ) -> _ToolCatalog:
        """Build trusted entries and atomically refresh the derived index.

        Args:
            capability_view (`_BoundCapabilityView`):
                Effective Runtime-open capability files to inspect.
            on_diagnostic (`Callable[[RuntimeDiagnostic], None] | None`):
                Optional callback for non-blocking metadata parse notices.

        Returns:
            The immutable Tool Catalog for the effective capability files.
        """

        tools_directory = Path(capability_view.root) / "tools"
        inspected: list[ToolEntry] = []
        for path in sorted(
            (path for path in tools_directory.iterdir() if path.name.endswith(".py")),
            key=lambda path: path.name,
        ):
            inspected.append(await _inspect_tool(path, capability_view, on_diagnostic))
        entries = tuple(inspected)
        catalog = cls(entries)
        _atomic_write(
            tools_directory / "index.md",
            catalog.render_index().encode("utf-8"),
        )
        return catalog

    def get(self, name: str) -> ToolEntry | None:
        return self._by_name.get(name)

    @property
    def valid_entries(self) -> tuple[ToolEntry, ...]:
        return tuple(entry for entry in self.entries if entry.valid)

    def render_index(self) -> str:
        """Render the model-readable projection without creating authority."""

        if not self.entries:
            return "# Tools\n\n_no tools_\n"

        lines = [
            "# Tools",
            "",
            (
                "Generated by cli-agent from the Runtime-open Capability View. "
                "This file is not an authority for validation or scheduling."
            ),
            "",
            (
                "| Name | Status | Provenance | Shadows Repertoire | "
                "Parallel Safe | Summary |"
            ),
            "|---|---|---|---|---|---|",
        ]
        for entry in self.entries:
            lines.append(
                (
                    "| {name} | {status} | {provenance} | {shadows} | "
                    "{parallel_safe} | {summary} |"
                ).format(
                    name=_markdown_cell(entry.name),
                    status=(
                        "valid"
                        if entry.valid
                        else f"invalid: {entry.validation_error or 'unknown error'}"
                    ).replace("|", "\\|"),
                    provenance=entry.provenance or "unknown",
                    shadows="yes" if entry.shadows_repertoire else "no",
                    parallel_safe="yes" if entry.parallel_safe else "no",
                    summary=_markdown_cell(entry.summary),
                )
            )
        return "\n".join(lines) + "\n"

    def render_info(self, name: str) -> tuple[str, bool]:
        entry = self.get(name)
        if entry is None:
            return f"Tool not found: {name}\n", False

        lines = [
            f"# Tool: {entry.name}",
            "",
            f"- Status: {'valid' if entry.valid else 'invalid'}",
            f"- Provenance: {entry.provenance or 'unknown'}",
            (f"- Shadows Repertoire: {'yes' if entry.shadows_repertoire else 'no'}"),
            f"- Parallel Safe: {'yes' if entry.parallel_safe else 'no'}",
        ]
        if entry.validation_error:
            lines.append(f"- Validation error: {entry.validation_error}")
        lines.extend(
            [
                "",
                entry.documentation
                or f"Tool {entry.name} exists, but no documentation was found.",
            ]
        )
        return "\n".join(lines).rstrip() + "\n", True


async def _inspect_tool(
    path: Path,
    capability_view: _BoundCapabilityView,
    on_diagnostic: Callable[[RuntimeDiagnostic], None] | None,
) -> ToolEntry:
    name = path.stem
    default_parallel_safe = _default_parallel_safe(name)
    relative = Path("tools") / path.name
    try:
        inspection = await capability_view.inspect(relative.as_posix())
    except ValueError as exc:
        return _invalid_entry(name, path, str(exc), default_parallel_safe)

    common = {
        "name": name,
        "path": path,
        "provenance": (
            inspection.provenance
            if inspection.provenance in {"repertoire", "workspace"}
            else None
        ),
        "shadows_repertoire": inspection.shadows_repertoire,
    }
    if not name.isidentifier() or keyword.iskeyword(name):
        return ToolEntry(
            **common,
            valid=False,
            validation_error=(
                "Tool filename stem must be a non-keyword Python identifier"
            ),
            documentation=None,
            parallel_safe=default_parallel_safe,
        )
    if not inspection.valid:
        return ToolEntry(
            **common,
            valid=False,
            validation_error=inspection.validation_error,
            documentation=None,
            parallel_safe=default_parallel_safe,
        )
    if not path.is_file():
        return ToolEntry(
            **common,
            valid=False,
            validation_error="Tool path must be a regular file",
            documentation=None,
            parallel_safe=default_parallel_safe,
        )

    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        return ToolEntry(
            **common,
            valid=False,
            validation_error=f"Tool source is not readable UTF-8: {exc}",
            documentation=None,
            parallel_safe=default_parallel_safe,
        )
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        location = f"line {exc.lineno}" if exc.lineno is not None else "unknown line"
        _emit_parallel_safe_diagnostic(
            on_diagnostic,
            name=name,
            relative=relative,
            default=default_parallel_safe,
            error=f"Python syntax error at {location}: {exc.msg}",
            stage="source",
        )
        return ToolEntry(
            **common,
            valid=False,
            validation_error=f"Python syntax error at {location}: {exc.msg}",
            documentation=None,
            parallel_safe=default_parallel_safe,
        )

    documentation = _read_companion_documentation(path)
    if documentation is None:
        documentation = ast.get_docstring(tree, clean=False)
    parallel_safe = _parse_parallel_safe(
        tree,
        default=default_parallel_safe,
        name=name,
        relative=relative,
        on_diagnostic=on_diagnostic,
    )
    return ToolEntry(
        **common,
        valid=True,
        validation_error=None,
        documentation=documentation,
        parallel_safe=parallel_safe,
    )


def _invalid_entry(
    name: str,
    path: Path,
    error: str,
    parallel_safe: bool,
) -> ToolEntry:
    return ToolEntry(
        name=name,
        path=path,
        provenance=None,
        shadows_repertoire=False,
        valid=False,
        validation_error=error,
        documentation=None,
        parallel_safe=parallel_safe,
    )


def _default_parallel_safe(name: str) -> bool:
    return not name.startswith(_MCP_TOOL_PREFIX)


def _parse_parallel_safe(
    tree: ast.Module,
    *,
    default: bool,
    name: str,
    relative: Path,
    on_diagnostic: Callable[[RuntimeDiagnostic], None] | None,
) -> bool:
    declarations: list[ast.expr | None] = []
    invalid_declaration = False

    for node in tree.body:
        if isinstance(node, ast.Assign):
            matching_targets = [
                target
                for target in node.targets
                if isinstance(target, ast.Name) and target.id == _PARALLEL_SAFE_NAME
            ]
            if matching_targets:
                if len(node.targets) != 1:
                    invalid_declaration = True
                declarations.append(node.value)
        elif isinstance(node, ast.AnnAssign):
            if (
                isinstance(node.target, ast.Name)
                and node.target.id == _PARALLEL_SAFE_NAME
            ):
                declarations.append(node.value)
        elif isinstance(node, ast.AugAssign):
            if (
                isinstance(node.target, ast.Name)
                and node.target.id == _PARALLEL_SAFE_NAME
            ):
                invalid_declaration = True

    if len(declarations) > 1:
        invalid_declaration = True
    elif len(declarations) == 1 and not _is_boolean_literal(declarations[0]):
        invalid_declaration = True

    if invalid_declaration:
        _emit_parallel_safe_diagnostic(
            on_diagnostic,
            name=name,
            relative=relative,
            default=default,
            error=_parallel_safe_error(declarations),
            stage="declaration",
        )
        return default
    if not declarations:
        return default
    value = declarations[0]
    assert value is not None
    assert isinstance(value, ast.Constant)
    assert type(value.value) is bool
    return value.value


def _is_boolean_literal(value: ast.expr | None) -> bool:
    return isinstance(value, ast.Constant) and type(value.value) is bool


def _parallel_safe_error(declarations: list[ast.expr | None]) -> str:
    if len(declarations) > 1:
        return "PARALLEL_SAFE must be declared exactly once"
    return "PARALLEL_SAFE must be a literal boolean"


def _emit_parallel_safe_diagnostic(
    on_diagnostic: Callable[[RuntimeDiagnostic], None] | None,
    *,
    name: str,
    relative: Path,
    default: bool,
    error: str,
    stage: str,
) -> None:
    if on_diagnostic is None:
        return
    on_diagnostic(
        RuntimeDiagnostic(
            kind="tools.parallel_safe_parse_failed",
            message=(
                f"Tool {name} parallel-safe metadata could not be parsed; "
                f"using default parallel_safe={default}"
            ),
            detail={
                "tool": name,
                "path": relative.as_posix(),
                "stage": stage,
                "error": error,
                "default_parallel_safe": default,
            },
        )
    )


def _read_companion_documentation(path: Path) -> str | None:
    documentation = path.with_suffix(".md")
    if not documentation.is_file():
        return None
    try:
        return documentation.read_text(encoding="utf-8").strip()
    except (OSError, UnicodeError):
        return None


def _markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")
