"""Runtime-owned MCP Tool stub rendering from discovery facts.

Rendering is pure: the deployment plane supplies the validated server
configs plus the provider-neutral discovery facts, and this module returns
the generated stub source for each discovered server. Stubs only call the
Runtime-materialized ``mcp_binding`` module; the renderer never holds a
transport stream, client, or subprocess, never reads env values, and never
writes Workspace files.
"""

from __future__ import annotations

import keyword
import re

from cli_agent.runtime._capability.mcp.facts import (
    MCPServerConfig,
    _MCPServerFacts,
)

MCP_STUB_PREFIX = "mcp_"

_STUB_RESERVED_NAMES = frozenset(
    {
        "call",
        "_call_mcp",
        "_format_result",
    }
)

_TYPE_HINTS = {
    "string": "str",
    "integer": "int",
    "boolean": "bool",
    "number": "float",
    "object": "dict",
    "array": "list",
}


def stub_filename(server_name: str) -> str:
    """Return the generated stub filename inside the Tools tree."""

    return f"{MCP_STUB_PREFIX}{server_name}.py"


def render_stub(
    config: MCPServerConfig,
    facts: _MCPServerFacts,
) -> str:
    """Render one generated Tool stub for a discovered MCP server."""

    header = (
        _stub_docstring(config, facts.tools)
        + "\n\nPARALLEL_SAFE = False\n"
        + "\nimport json\n\n"
        + "from mcp_binding import call_tool as _call_mcp\n"
    )
    used: set[str] = set(_STUB_RESERVED_NAMES)
    functions = [
        _tool_function(config.name, tool, func_name=_function_name(tool.name, used))
        for tool in facts.tools
    ]
    body = "\n\n".join([*functions, _call_runtime(config.name)])
    return header + "\n\n" + body + "\n"


def _stub_docstring(
    config: MCPServerConfig,
    tools: tuple,
) -> str:
    lines = [
        '"""',
        f"MCP Server ({config.transport}): {config.name}",
        "Generated by cli-agent from the Repertoire _mcp configuration.",
        "",
        "Usage:",
        f'  tools run "tools.mcp_{config.name}.<function>(...)"',
        "",
        "Available tools:",
    ]
    if tools:
        lines.extend(
            f"  - {tool.name}: {_single_line(tool.description)}" for tool in tools
        )
    else:
        lines.append("  (no tools discovered)")
    lines.append('"""')
    return "\n".join(lines)


def _tool_function(server_name: str, tool, *, func_name: str) -> str:
    schema = tool.input_schema or {}
    properties = schema.get("properties") or {}
    required = schema.get("required") or []

    params = []
    for prop_name, prop_info in properties.items():
        type_hint = _type_hint(prop_info.get("type"))
        default = repr(prop_info.get("default"))
        if prop_name in required:
            params.append(f"{prop_name}: {type_hint}" if type_hint else prop_name)
        elif type_hint:
            params.append(f"{prop_name}: {type_hint} = {default}")
        else:
            params.append(f"{prop_name}={default}")
    signature = ", ".join(params)
    return (
        "def " + func_name + "(" + signature + "):\n"
        '    """' + _single_line(tool.description).replace('"""', '\\"\\"\\"') + '"""\n'
        "    return _format_result(_call_mcp("
        + repr(server_name)
        + ", "
        + repr(tool.name)
        + ", {k: v for k, v in locals().items() if v is not None}))\n"
    )


def _call_runtime(server_name: str) -> str:
    return (
        "def call(tool_name, **kwargs):\n"
        '    """Call any MCP tool by name."""\n'
        "    return _format_result(_call_mcp("
        + repr(server_name)
        + ", tool_name, {k: v for k, v in kwargs.items() if v is not None}))\n"
        "\n"
        "\n"
        "def _format_result(result):\n"
        "    if result.is_error:\n"
        "        texts = [item.text for item in result.content "
        "if hasattr(item, 'text')]\n"
        "        raise RuntimeError(texts[0] if texts else "
        "'MCP tool returned an error')\n"
        "    if result.structured_content is not None:\n"
        "        return json.dumps(result.structured_content, ensure_ascii=False)\n"
        "    parts = []\n"
        "    for item in result.content:\n"
        "        if hasattr(item, 'text'):\n"
        "            parts.append(item.text)\n"
        "        elif hasattr(item, 'data'):\n"
        "            parts.append(str(item.data))\n"
        "    return '\\n'.join(parts) if parts else None\n"
    )


def _single_line(value: str) -> str:
    return " ".join(value.split())


def _type_hint(schema_type: object) -> str:
    return _TYPE_HINTS.get(schema_type, "")


def _function_name(raw: str, used: set[str]) -> str:
    candidate = re.sub(r"\W", "_", raw)
    if not candidate or candidate[0].isdigit():
        candidate = "_" + candidate
    if keyword.iskeyword(candidate):
        candidate = candidate + "_"
    base = candidate
    counter = 2
    while candidate in used:
        candidate = f"{base}_{counter}"
        counter += 1
    used.add(candidate)
    return candidate
