"""Runtime-open Tool Catalog derived from the Capability View."""

from __future__ import annotations

import ast
import keyword
from pathlib import Path

from cli_agent.runtime.capability.tools.facts import ToolEntry
from cli_agent.runtime.capability.view import _CapabilityView
from cli_agent.runtime.capability.workspace import _atomic_write


class _ToolCatalog:
    """Immutable lookup and generated projections for effective Tool files."""

    def __init__(self, entries: tuple[ToolEntry, ...]) -> None:
        self.entries = entries
        self._by_name = {entry.name: entry for entry in entries}

    @classmethod
    def reconcile(cls, capability_view: _CapabilityView) -> _ToolCatalog:
        """Build trusted entries and atomically refresh the derived index."""

        tools_directory = capability_view.root / "tools"
        entries = tuple(
            _inspect_tool(path, capability_view)
            for path in sorted(
                (
                    path
                    for path in tools_directory.iterdir()
                    if path.name.endswith(".py")
                ),
                key=lambda path: path.name,
            )
        )
        catalog = cls(entries)
        _atomic_write(
            tools_directory / "index.md",
            catalog.render_index().encode("utf-8"),
        )
        return catalog

    def get(self, name: str) -> ToolEntry | None:
        return self._by_name.get(name)

    @property
    def valid_entries(self) -> tuple[ToolEntry, ...]:
        return tuple(entry for entry in self.entries if entry.valid)

    def render_index(self) -> str:
        """Render the model-readable projection without creating authority."""

        if not self.entries:
            return "# Tools\n\n_no tools_\n"

        lines = [
            "# Tools",
            "",
            (
                "Generated by cli-agent from the Runtime-open Capability View. "
                "This file is not an authority for validation or scheduling."
            ),
            "",
            "| Name | Status | Provenance | Shadows Repertoire | Summary |",
            "|---|---|---|---|---|",
        ]
        for entry in self.entries:
            lines.append(
                "| {name} | {status} | {provenance} | {shadows} | {summary} |".format(
                    name=_markdown_cell(entry.name),
                    status=(
                        "valid"
                        if entry.valid
                        else f"invalid: {entry.validation_error or 'unknown error'}"
                    ).replace("|", "\\|"),
                    provenance=entry.provenance or "unknown",
                    shadows="yes" if entry.shadows_repertoire else "no",
                    summary=_markdown_cell(entry.summary),
                )
            )
        return "\n".join(lines) + "\n"

    def render_info(self, name: str) -> tuple[str, bool]:
        entry = self.get(name)
        if entry is None:
            return f"Tool not found: {name}\n", False

        lines = [
            f"# Tool: {entry.name}",
            "",
            f"- Status: {'valid' if entry.valid else 'invalid'}",
            f"- Provenance: {entry.provenance or 'unknown'}",
            (
                "- Shadows Repertoire: "
                f"{'yes' if entry.shadows_repertoire else 'no'}"
            ),
        ]
        if entry.validation_error:
            lines.append(f"- Validation error: {entry.validation_error}")
        lines.extend(
            [
                "",
                entry.documentation
                or f"Tool {entry.name} exists, but no documentation was found.",
            ]
        )
        return "\n".join(lines).rstrip() + "\n", True


def _inspect_tool(path: Path, capability_view: _CapabilityView) -> ToolEntry:
    name = path.stem
    relative = Path("tools") / path.name
    try:
        inspection = capability_view.inspect(relative)
    except ValueError as exc:
        return _invalid_entry(name, path, str(exc))

    common = {
        "name": name,
        "path": path,
        "provenance": (
            inspection.provenance
            if inspection.provenance in {"repertoire", "workspace"}
            else None
        ),
        "shadows_repertoire": inspection.shadows_repertoire,
    }
    if not name.isidentifier() or keyword.iskeyword(name):
        return ToolEntry(
            **common,
            valid=False,
            validation_error=(
                "Tool filename stem must be a non-keyword Python identifier"
            ),
            documentation=None,
        )
    if not inspection.valid:
        return ToolEntry(
            **common,
            valid=False,
            validation_error=inspection.validation_error,
            documentation=None,
        )
    if not path.is_file():
        return ToolEntry(
            **common,
            valid=False,
            validation_error="Tool path must be a regular file",
            documentation=None,
        )

    try:
        source = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as exc:
        return ToolEntry(
            **common,
            valid=False,
            validation_error=f"Tool source is not readable UTF-8: {exc}",
            documentation=None,
        )
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        location = f"line {exc.lineno}" if exc.lineno is not None else "unknown line"
        return ToolEntry(
            **common,
            valid=False,
            validation_error=f"Python syntax error at {location}: {exc.msg}",
            documentation=None,
        )

    documentation = _read_companion_documentation(path)
    if documentation is None:
        documentation = ast.get_docstring(tree, clean=False)
    return ToolEntry(
        **common,
        valid=True,
        validation_error=None,
        documentation=documentation,
    )


def _invalid_entry(name: str, path: Path, error: str) -> ToolEntry:
    return ToolEntry(
        name=name,
        path=path,
        provenance=None,
        shadows_repertoire=False,
        valid=False,
        validation_error=error,
        documentation=None,
    )


def _read_companion_documentation(path: Path) -> str | None:
    documentation = path.with_suffix(".md")
    if not documentation.is_file():
        return None
    try:
        return documentation.read_text(encoding="utf-8").strip()
    except (OSError, UnicodeError):
        return None


def _markdown_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\r", " ").replace("\n", " ")
